// <auto-generated />
namespace Mango.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ProductCategoryUrlSlug : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ProductCategoryUrlSlug));
        
        string IMigrationMetadata.Id
        {
            get { return "201503201502091_ProductCategoryUrlSlug"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
