// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
#pragma warning disable 1591, 3008, 3009, 0108
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Mango.Web.Controllers
{
    public partial class UtilityController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public UtilityController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected UtilityController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.FileStreamResult BlobImage()
        {
            return new T4MVC_System_Web_Mvc_FileStreamResult(Area, Name, ActionNames.BlobImage);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public UtilityController Actions { get { return MVC.Utility; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Utility";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Utility";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string BlobImage = "BlobImage";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string BlobImage = "BlobImage";
        }


        static readonly ActionParamsClass_BlobImage s_params_BlobImage = new ActionParamsClass_BlobImage();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_BlobImage BlobImageParams { get { return s_params_BlobImage; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_BlobImage
        {
            public readonly string container = "container";
            public readonly string blobId = "blobId";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
            }
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_UtilityController : Mango.Web.Controllers.UtilityController
    {
        public T4MVC_UtilityController() : base(Dummy.Instance) { }

        [NonAction]
        partial void BlobImageOverride(T4MVC_System_Web_Mvc_FileStreamResult callInfo, string container, string blobId);

        [NonAction]
        public override System.Web.Mvc.FileStreamResult BlobImage(string container, string blobId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_FileStreamResult(Area, Name, ActionNames.BlobImage);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "container", container);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "blobId", blobId);
            BlobImageOverride(callInfo, container, blobId);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108
